// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXpAI14M0BIkL2Q4koFAstLCwGpn1xJr4',
    appId: '1:131652790742:web:dbe6efe415984a6f045c77',
    messagingSenderId: '131652790742',
    projectId: 'chatapp-26522',
    authDomain: 'chatapp-26522.firebaseapp.com',
    storageBucket: 'chatapp-26522.firebasestorage.app',
    measurementId: 'G-V7SYQ49W65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnqaPhiIMNzgAcLSNgptxQEzBzAQKDVc',
    appId: '1:131652790742:android:363ea48cb51805e7045c77',
    messagingSenderId: '131652790742',
    projectId: 'chatapp-26522',
    storageBucket: 'chatapp-26522.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAznHhYAF6gtkSjvssZcPQ1GY4Vid0lrSY',
    appId: '1:131652790742:ios:2ad601d2d1ed98f0045c77',
    messagingSenderId: '131652790742',
    projectId: 'chatapp-26522',
    storageBucket: 'chatapp-26522.firebasestorage.app',
    iosBundleId: 'com.example.basicChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAznHhYAF6gtkSjvssZcPQ1GY4Vid0lrSY',
    appId: '1:131652790742:ios:2ad601d2d1ed98f0045c77',
    messagingSenderId: '131652790742',
    projectId: 'chatapp-26522',
    storageBucket: 'chatapp-26522.firebasestorage.app',
    iosBundleId: 'com.example.basicChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXpAI14M0BIkL2Q4koFAstLCwGpn1xJr4',
    appId: '1:131652790742:web:7cd36f01077b4133045c77',
    messagingSenderId: '131652790742',
    projectId: 'chatapp-26522',
    authDomain: 'chatapp-26522.firebaseapp.com',
    storageBucket: 'chatapp-26522.firebasestorage.app',
    measurementId: 'G-ZBGMENG64W',
  );
}
